### ISSUE TITLE
Why minSdkVersion 16?

### ISSUE THREAD

**Issue by jmtt89** [iZettle/android-html2bitmap#24]
I check your code and don't see anything you need that min version, are some reason for that restriction?

**Comment by erikeelde** [comment]
Not sure, I can look into it. Is your requirement to use minSdk 14? Or do you have even lower minSdks in mind?

**Comment by jmtt89** [comment]
For me, level 14 is enough

El 11 oct. 2018 03:39, "Erik Eelde" <notifications@github.com> escribió:

Not sure, I can look into it. Is your requirement to use minSdk 14? Or do
you have even lower minSdks in mind?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iZettle/android-html2bitmap/issues/24#issuecomment-428853318>,
or mute the thread

**Comment by erikeelde** [comment]
https://github.com/iZettle/android-html2bitmap/pull/25

**Comment by erikeelde** [comment]
https://github.com/iZettle/android-html2bitmap/releases/tag/1.9
