### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro

### ISSUE THREAD

**Issue by ismdcf** [iZettle/android-html2bitmap#30]
Getting the above error when try to integrate in my app which has couple of product flavours. For now used the following SO hack to fix. Can this be fixed, if so please let me know ready to contribute.
https://stackoverflow.com/questions/52518378/more-than-one-file-was-found-with-os-independent-path-meta-inf-proguard-android

**Comment by erikeelde** [comment]
I've sent a ping to @MarijanGazica to have him help release a fix for this. Thanks for reaching out.

**Comment by MarijanGazica** [comment]
Hi @ismdcf 
Have you tried enabling `jetifier` if it is not already enabled?
Also, Android Gradle plugin v3.3.* should exclude those files by default. Try updating it as well.
Please let us know if this helps.

**Comment by erikeelde** [comment]
@MarijanGazica I think you can close this.. :)
